[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# React SPA fallback (supports client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
