name: Feature request
description: Suggest an idea or improvement for the project
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing an idea! Please complete the sections below.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? Who is impacted?
      placeholder: It’s hard to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature and how it should work.
      placeholder: Add a control that...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you’ve considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, screenshots, links, or related issues.
